/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as VendorStatementRouteImport } from './routes/vendor.statement'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentOrdersRouteImport } from './routes/student.orders'
import { Route as StudentFavoritesRouteImport } from './routes/student.favorites'
import { Route as StudentCheckoutRouteImport } from './routes/student.checkout'
import { Route as StudentCartRouteImport } from './routes/student.cart'
import { Route as SponsorPayloadRouteImport } from './routes/sponsor.$payload'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as RiderTripsRouteImport } from './routes/rider.trips'
import { Route as RiderStatementRouteImport } from './routes/rider.statement'
import { Route as RiderProfileRouteImport } from './routes/rider.profile'
import { Route as RiderEarningsRouteImport } from './routes/rider.earnings'
import { Route as StudentTrackIdRouteImport } from './routes/student.track.$id'
import { Route as StudentShopIdRouteImport } from './routes/student.shop.$id'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const VendorStatementRoute = VendorStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOrdersRoute = StudentOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFavoritesRoute = StudentFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCheckoutRoute = StudentCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCartRoute = StudentCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StudentRoute,
} as any)
const SponsorPayloadRoute = SponsorPayloadRouteImport.update({
  id: '/sponsor/$payload',
  path: '/sponsor/$payload',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderTripsRoute = RiderTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => RiderRoute,
} as any)
const RiderStatementRoute = RiderStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => RiderRoute,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RiderRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRoute,
} as any)
const StudentTrackIdRoute = StudentTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentShopIdRoute = StudentShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rider': typeof RiderRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/statement': typeof RiderStatementRoute
  '/rider/trips': typeof RiderTripsRoute
  '/shop/$id': typeof ShopIdRoute
  '/sponsor/$payload': typeof SponsorPayloadRoute
  '/student/cart': typeof StudentCartRoute
  '/student/checkout': typeof StudentCheckoutRoute
  '/student/favorites': typeof StudentFavoritesRoute
  '/student/orders': typeof StudentOrdersRoute
  '/student/profile': typeof StudentProfileRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/statement': typeof VendorStatementRoute
  '/rider/': typeof RiderIndexRoute
  '/student/': typeof StudentIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/student/shop/$id': typeof StudentShopIdRoute
  '/student/track/$id': typeof StudentTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/statement': typeof RiderStatementRoute
  '/rider/trips': typeof RiderTripsRoute
  '/shop/$id': typeof ShopIdRoute
  '/sponsor/$payload': typeof SponsorPayloadRoute
  '/student/cart': typeof StudentCartRoute
  '/student/checkout': typeof StudentCheckoutRoute
  '/student/favorites': typeof StudentFavoritesRoute
  '/student/orders': typeof StudentOrdersRoute
  '/student/profile': typeof StudentProfileRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/statement': typeof VendorStatementRoute
  '/rider': typeof RiderIndexRoute
  '/student': typeof StudentIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/student/shop/$id': typeof StudentShopIdRoute
  '/student/track/$id': typeof StudentTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rider': typeof RiderRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/statement': typeof RiderStatementRoute
  '/rider/trips': typeof RiderTripsRoute
  '/shop/$id': typeof ShopIdRoute
  '/sponsor/$payload': typeof SponsorPayloadRoute
  '/student/cart': typeof StudentCartRoute
  '/student/checkout': typeof StudentCheckoutRoute
  '/student/favorites': typeof StudentFavoritesRoute
  '/student/orders': typeof StudentOrdersRoute
  '/student/profile': typeof StudentProfileRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/statement': typeof VendorStatementRoute
  '/rider/': typeof RiderIndexRoute
  '/student/': typeof StudentIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/student/shop/$id': typeof StudentShopIdRoute
  '/student/track/$id': typeof StudentTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rider'
    | '/student'
    | '/vendor'
    | '/rider/earnings'
    | '/rider/profile'
    | '/rider/statement'
    | '/rider/trips'
    | '/shop/$id'
    | '/sponsor/$payload'
    | '/student/cart'
    | '/student/checkout'
    | '/student/favorites'
    | '/student/orders'
    | '/student/profile'
    | '/vendor/analytics'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/statement'
    | '/rider/'
    | '/student/'
    | '/vendor/'
    | '/student/shop/$id'
    | '/student/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/rider/earnings'
    | '/rider/profile'
    | '/rider/statement'
    | '/rider/trips'
    | '/shop/$id'
    | '/sponsor/$payload'
    | '/student/cart'
    | '/student/checkout'
    | '/student/favorites'
    | '/student/orders'
    | '/student/profile'
    | '/vendor/analytics'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/statement'
    | '/rider'
    | '/student'
    | '/vendor'
    | '/student/shop/$id'
    | '/student/track/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/rider'
    | '/student'
    | '/vendor'
    | '/rider/earnings'
    | '/rider/profile'
    | '/rider/statement'
    | '/rider/trips'
    | '/shop/$id'
    | '/sponsor/$payload'
    | '/student/cart'
    | '/student/checkout'
    | '/student/favorites'
    | '/student/orders'
    | '/student/profile'
    | '/vendor/analytics'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/statement'
    | '/rider/'
    | '/student/'
    | '/vendor/'
    | '/student/shop/$id'
    | '/student/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  RiderRoute: typeof RiderRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  ShopIdRoute: typeof ShopIdRoute
  SponsorPayloadRoute: typeof SponsorPayloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/vendor/statement': {
      id: '/vendor/statement'
      path: '/statement'
      fullPath: '/vendor/statement'
      preLoaderRoute: typeof VendorStatementRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/orders': {
      id: '/student/orders'
      path: '/orders'
      fullPath: '/student/orders'
      preLoaderRoute: typeof StudentOrdersRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/favorites': {
      id: '/student/favorites'
      path: '/favorites'
      fullPath: '/student/favorites'
      preLoaderRoute: typeof StudentFavoritesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/checkout': {
      id: '/student/checkout'
      path: '/checkout'
      fullPath: '/student/checkout'
      preLoaderRoute: typeof StudentCheckoutRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/cart': {
      id: '/student/cart'
      path: '/cart'
      fullPath: '/student/cart'
      preLoaderRoute: typeof StudentCartRouteImport
      parentRoute: typeof StudentRoute
    }
    '/sponsor/$payload': {
      id: '/sponsor/$payload'
      path: '/sponsor/$payload'
      fullPath: '/sponsor/$payload'
      preLoaderRoute: typeof SponsorPayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/trips': {
      id: '/rider/trips'
      path: '/trips'
      fullPath: '/rider/trips'
      preLoaderRoute: typeof RiderTripsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/statement': {
      id: '/rider/statement'
      path: '/statement'
      fullPath: '/rider/statement'
      preLoaderRoute: typeof RiderStatementRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/student/track/$id': {
      id: '/student/track/$id'
      path: '/track/$id'
      fullPath: '/student/track/$id'
      preLoaderRoute: typeof StudentTrackIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/shop/$id': {
      id: '/student/shop/$id'
      path: '/shop/$id'
      fullPath: '/student/shop/$id'
      preLoaderRoute: typeof StudentShopIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface RiderRouteChildren {
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderStatementRoute: typeof RiderStatementRoute
  RiderTripsRoute: typeof RiderTripsRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderEarningsRoute: RiderEarningsRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderStatementRoute: RiderStatementRoute,
  RiderTripsRoute: RiderTripsRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

interface StudentRouteChildren {
  StudentCartRoute: typeof StudentCartRoute
  StudentCheckoutRoute: typeof StudentCheckoutRoute
  StudentFavoritesRoute: typeof StudentFavoritesRoute
  StudentOrdersRoute: typeof StudentOrdersRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentShopIdRoute: typeof StudentShopIdRoute
  StudentTrackIdRoute: typeof StudentTrackIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCartRoute: StudentCartRoute,
  StudentCheckoutRoute: StudentCheckoutRoute,
  StudentFavoritesRoute: StudentFavoritesRoute,
  StudentOrdersRoute: StudentOrdersRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentShopIdRoute: StudentShopIdRoute,
  StudentTrackIdRoute: StudentTrackIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface VendorRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorStatementRoute: typeof VendorStatementRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorStatementRoute: VendorStatementRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RiderRoute: RiderRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  ShopIdRoute: ShopIdRoute,
  SponsorPayloadRoute: SponsorPayloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
